### ISSUE TITLE
Fetch Language list supported by the server

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/Bookalope-CEP#16]
We need to populate the list of available languages for the Bookflow metadata, ideally from the list of available languages on the server.

Currently we don’t have an [API endpoint](https://github.com/bookalope/Bookalope/blob/master/API.md) for that so one needs to be added.

Fetching that information requires auth, though, so that entering a token or switching beta/prod servers will require to fetch data and refresh the extension UI.

**Comment by wold5** [comment]
Hi, I submitted a PR here: https://github.com/bookalope/InDesign-CEP/pull/17

**Comment by jenstroeger** [comment]
Thanks @wold5! I added an endpoint `GET /api/configuration` (which requires the auth token) and it returns a JSON object of this shape:
```json
{
    "languages": [
        {
            "code": "de_DE",
            "endonym": "Deutsch (Deutschland)"
        },
        {
            "code": "en_AU",
            "endonym": "English (Australia)"
        },
        ...
        {
            "code": "he_IL",
            "endonym": "עברית (ישראל)"
        },
        {
            "code": "ar_SY",
            "endonym": "العربية (سوريا)"
        },
        {
            "code": "fa_IR",
            "endonym": "فارسی (ایران)"
        }
    ],
    "styles": {
        ...
    }
}
```
We can ignore the `"styles"` object for this issue.

**Comment by jenstroeger** [comment]
Release [v1.4.0](https://github.com/bookalope/InDesign-CEP/releases/tag/v1.4.0). Thank you @wold5 🤓
